-- Update the survey responses to have more variety and realistic feedback
UPDATE temp_muganga_survey_responses SET 
  cost_feedback = CASE 
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 0) THEN 'Price is fair for quality therapy'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 1) THEN 'A bit expensive but worth it for mental health'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 2) THEN 'Could be cheaper for students like me'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 3) THEN 'No issues with cost, very reasonable'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 4) THEN 'Monthly payment works well for my budget'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 5) THEN 'Too expensive for regular sessions'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 6) THEN 'Worth every franc, excellent value'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 7) THEN 'Price is affordable and fair'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 8) THEN 'Would like payment plans or discounts'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 9) THEN 'Cost is reasonable for professional therapy'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 10) THEN 'Happy to pay for quality mental health care'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 11) THEN 'Expensive but necessary investment in myself'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 12) THEN 'No cost concerns, very satisfied'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 13) THEN 'Price could be lower for better accessibility'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 14) THEN 'Great value for professional counseling'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 15) THEN 'Cost is high but therapy quality justifies it'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 16) THEN 'No financial burden, very manageable'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 17) THEN 'Would prefer sliding scale pricing'
    ELSE 'Price is fair for the service provided'
  END,
  communication_preference = CASE 
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 0) THEN 'In-app video calls would be perfect'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 1) THEN 'Please add video calling feature in app'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 2) THEN 'Phone calls work fine for me'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 3) THEN 'In-app audio calls would be more convenient'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 4) THEN 'Google Meet is okay but in-app better'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 5) THEN 'Need in-app messaging for privacy'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 6) THEN 'Video calls in app would be amazing'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 7) THEN 'Current system works but in-app is better'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 8) THEN 'Please integrate video calling feature'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 9) THEN 'In-app calls would ensure more privacy'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 10) THEN 'Happy with phone calls for now'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 11) THEN 'In-app video would be more professional'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 12) THEN 'Audio calls in app would be convenient'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 13) THEN 'Google Meet works but app integration needed'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 14) THEN 'Please add secure in-app calling'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 15) THEN 'In-app communication would be perfect'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 16) THEN 'Current phone system is adequate'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 17) THEN 'Would love in-app video sessions'
    ELSE 'In-app calling would be more convenient'
  END,
  overall_experience = CASE 
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 0) THEN 'Excellent therapy, very satisfied with my female therapist'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 1) THEN 'Good experience but need more flexible scheduling'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 2) THEN 'Amazing service, my male therapist is very understanding'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 3) THEN 'Truly grateful for this service, life-changing experience'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 4) THEN 'Great therapy but wish I could choose therapist gender'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 5) THEN 'Professional service, would prefer evening sessions'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 6) THEN 'Outstanding support, my therapist saved my life'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 7) THEN 'Good service but need weekend appointment options'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 8) THEN 'Very satisfied, female therapist made me comfortable'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 9) THEN 'Helpful therapy, need more session time flexibility'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 10) THEN 'Grateful beyond words, therapy changed my perspective'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 11) THEN 'Excellent male therapist, very professional approach'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 12) THEN 'Good experience but scheduling is too rigid'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 13) THEN 'Life-saving service, eternally grateful for the support'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 14) THEN 'Quality therapy, wish I could request specific therapist'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 15) THEN 'Excellent service, need more booking flexibility'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 16) THEN 'Blessed to have found this service, truly transformative'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 17) THEN 'Great therapy experience, female therapist understood me'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 18) THEN 'Professional service but need earlier morning slots'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 19) THEN 'Outstanding therapy, my therapist is a miracle worker'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 20) THEN 'Good experience, would prefer male therapist option'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 21) THEN 'Satisfied with service, scheduling could be improved'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 22) THEN 'Forever grateful, therapy gave me hope again'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 23) THEN 'Excellent therapy, wish sessions were longer'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 24) THEN 'Great service, female therapist made all the difference'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 25) THEN 'Professional support, need more appointment flexibility'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 26) THEN 'Amazing experience, truly thankful for this service'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 27) THEN 'Good therapy but prefer choosing therapist gender'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 28) THEN 'Quality service, scheduling system needs improvement'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 29) THEN 'Life-changing therapy, my therapist is exceptional'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 30) THEN 'Satisfied overall, need more session time options'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 31) THEN 'Grateful for professional support and understanding'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 32) THEN 'Excellent male therapist, very comfortable sessions'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 33) THEN 'Good service, wish I could book sessions in advance'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 34) THEN 'Outstanding therapy experience, highly recommend'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 35) THEN 'Professional service, need more therapist options'
    WHEN id = (SELECT id FROM temp_muganga_survey_responses ORDER BY created_at LIMIT 1 OFFSET 36) THEN 'Blessed to receive this support, truly grateful'
    ELSE 'Great therapy experience, very professional service'
  END;